import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';
import { clsx } from 'clsx';
import { ClerkProvider } from '@clerk/nextjs';
import NavBar from '@/components/layout/NavBar2';
import Container from '@/components/layout/Container';
import SocketProvider from '@/providers/SocketProvider';

const geistSans = localFont({
	src: './fonts/GeistVF.woff',
	variable: '--font-geist-sans',
	weight: '100 900',
});
const geistMono = localFont({
	src: './fonts/GeistMonoVF.woff',
	variable: '--font-geist-mono',
	weight: '100 900',
});

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en' className='light'>
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased`}
			>
				<main className='flex flex-col min-h-screen '>{children}</main>
			</body>
		</html>
	);
}
